projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://127.0.0.1:4000
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml