version: '3.3'
services:
  mysql:
    image: mysql:5.6
    volumes:
      - /root/data/mysql:/var/lib/mysql
      - ./conf/:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=123456
volumes:
  mysql: